name = input()
price = int(input())
weight = float(input())
money = int(input())
print(f'Чек')
print(f'{name} - {int(weight)}кг - {price}руб/кг')
print(f'Итого: {int(weight * price)}руб')
print(f'Внесено: {money}руб')
print(f'Сдача: {money - int(weight * price)}руб')